services:
  mysql:
    image: mysql:8.0
    container_name: rp-mysql
    env_file: .env
    command: [ "mysqld","--default-authentication-plugin=mysql_native_password",
               "--character-set-server=utf8mb4","--collation-server=utf8mb4_general_ci" ]
    ports: [ "3306:3306" ]
    volumes: [ "db_data:/var/lib/mysql" ]

  adminer:
    image: adminer
    container_name: rp-adminer
    depends_on: [ mysql ]
    ports: [ "8081:8080" ]

volumes:
  db_data: