# src/main/resources/application-dev.yml
spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/${MYSQL_DATABASE}?useSSL=false&allowPublicKeyRetrieval=true&characterEncoding=UTF-8&serverTimezone=Asia/Seoul
    username: ${MYSQL_USER}
    password: ${MYSQL_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: validate # 스키마는 Flyway가 책임지고, JPA는 검증만.
    open-in-view: false
    properties:
      hibernate.hibernate.format_sql: ture

  flyway:
    enabled: true
    locations: classpath:db/migration

springdoc:
  swagger-ui:
    path: /swagger-ui
    display-request-duration: true
  api-docs:
    path: /v3/api-docs
  packages-to-scan: io.routepickapi
  paths-to-match: /**